### ISSUE TITLE
Can anyone confirm this is still working.

### ISSUE THREAD

**Issue by generic-user** [Gruntfuggly/banish-pointer#1]
I just discovered this extension, I installed it. But it does not seem to be doing anything.

Am I missing something?

**Comment by tellmewhy12** [comment]
It did work for me, I forgot installing this and wondered why my mouse randomly displaced xD It would be great to have an extension like this that hides your cursor while typing instead of moving it, which can be a bit annoying when copy pasting a lot

**Comment by Gruntfuggly** [comment]
The extension was only a hack really - it doesn't work very well. It would be great if vscode could hide the cursor once you start typing. It's possible with third party tools on linux, but not Windows or MacOS (as far as I know).

**Comment by generic-user** [comment]
When I use the executable directly from command line it works. Not when installed in VSC.

Anyway, I do no longer use it, [I found an Autohotkey script which does the trick for me. ](https://gist.github.com/generic-user/bb54f9b063903a2b57f19bac8c7921d0)
